### ISSUE TITLE
Use CAR files For Retrieval

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/go-retrieval-market-project#9]
In:
- Replace current unsealing logic w/ FileStore & PieceIO modules
- Should use PieceIO.ReadPiece
- Add returning of intermediate nodes

Out:
- Worrying about actually querying with payload CIDs etc (v1 protocol

**Comment by mikeal** [comment]
you me and @rvagg should talk about this. we’re working on a spec for CAR and potential changes/improvements that are ostensibly meant for the retrieval use case.
